### ISSUE TITLE
I cant understand how this works..

### ISSUE THREAD

**Issue by profesionalleet1337** [The-Osint-Toolbox/Vehicle-OSINT#1]
Please explain, how to use this ? Could be installed/runned on google cloud shell/kali linux or what?

**Comment by profesionalleet1337** [comment]
@cqcore Why you are closing the issue, when you didn't answear/ explain ? Are you just share some "source" for osint, or this is a tool, that gathered them in one, and can be used easly ?

**Comment by The-Osint-Toolbox** [comment]
Dear @profesionalleet1337 I have not used every OSINT resource I have listed, which I have explained in my Readme. I get numeorus requests about how to use some of the resources, unfortunately I do not have enough time to be able to respond, as it takes a lot of my time collating all the resources, for the benefit of the OSINT community.

**Comment by profesionalleet1337** [comment]
> Dear @profesionalleet1337 I have not used every OSINT resource I have listed, which I have explained in my Readme. I get numeorus requests about how to use some of the resources, unfortunately I do not have enough time to be able to respond, as it takes a lot of my time collating all the resources, for the benefit of the OSINT community.

Yeah, I read all.. But this is likely not for Europe cars.. Could u make/ upload resource list for Europe , for example I'm looking for country like Bulgaria ? What could be done ?
